#!/usr/bin/python
import sys

import i3


USAGE = """i3-focus

usage: i3-focus {next-window|prev-window}"""


def windows_in_current_workspace():
    # Get the current workspace
    workspace = i3.filter(i3.get_workspaces(), focused=True)[0]
    # Find the node corresponding to the workspace
    wsnode = i3.filter(i3.get_tree(), num=workspace['num'], name=workspace['name'])[0]
    # Enumerate windows in the workspace
    windows = i3.filter(wsnode['nodes'] + wsnode['floating_nodes'], nodes=[])
    return windows


def next_window():
    windows = windows_in_current_workspace()
    i = 0
    while not windows[i]['focused']:
        i += 1
    j = (i + 1) % len(windows)
    target_id = windows[j]['id']
    return target_id


def prev_window():
    windows = windows_in_current_workspace()
    i = 0
    while not windows[i]['focused']:
        i += 1
    j = (i - 1) % len(windows)
    target_id = windows[j]['id']
    return target_id


if __name__ == '__main__':
    if len(sys.argv) == 2:
        if sys.argv[1] == 'next-window':
            print(next_window())
        elif sys.argv[1] == 'prev-window':
            print(prev_window())
        else:
            print(USAGE, file=sys.stderr)
    else:
        print(USAGE, file=sys.stderr)
